// Known Holidays
Table.FromRecords({  
  [Holiday = "New Year's", #"Observed?" = "Yes"],
  [Holiday = "Martin Luther King Day", #"Observed?" = "Yes"],
  [Holiday = "President's Day", #"Observed?" = "Yes"],
  [Holiday = "Memorial Day", #"Observed?" = "Yes"],
  [Holiday = "4th of July", #"Observed?" = "Yes"],
  [Holiday = "Labor Day", #"Observed?" = "Yes"],
  [Holiday = "Thanksgiving", #"Observed?" = "Yes"],
  [Holiday = "Day After Thanksgiving", #"Observed?" = "Yes"],
  [Holiday = "Christmas Eve", #"Observed?" = "Yes"],
  [Holiday = "Christmas", #"Observed?" = "Yes"],
  [Holiday = "New Year's Eve", #"Observed?" = "Yes"]
})
